[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
  'ls -la',
  'cd backend/ShoeStore',
  'ls -la',
  'dotnet restore',
  'dotnet build -c Release'
]

[start]
cmd = "cd backend/ShoeStore/ShoeStore && dotnet run --urls http://0.0.0.0:${PORT:-8080}"